// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiDdNRD7HiOPhVljAn-mCOfXAK2mtu3_A',
    appId: '1:648791294568:web:95d2b88135628233e5f1dd',
    messagingSenderId: '648791294568',
    projectId: 'today-news-7520b',
    authDomain: 'today-news-7520b.firebaseapp.com',
    storageBucket: 'today-news-7520b.appspot.com',
    measurementId: 'G-E06XT5XWPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRTWIiYVEpZhbYoEvf2uWE5jvXNXxz8BE',
    appId: '1:648791294568:android:f74b15470bc359cee5f1dd',
    messagingSenderId: '648791294568',
    projectId: 'today-news-7520b',
    storageBucket: 'today-news-7520b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc-noePESgAxMtfriYTO_tgRqPcrPohUM',
    appId: '1:648791294568:ios:bd162e836fe51f11e5f1dd',
    messagingSenderId: '648791294568',
    projectId: 'today-news-7520b',
    storageBucket: 'today-news-7520b.appspot.com',
    iosBundleId: 'com.example.todayNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc-noePESgAxMtfriYTO_tgRqPcrPohUM',
    appId: '1:648791294568:ios:bd162e836fe51f11e5f1dd',
    messagingSenderId: '648791294568',
    projectId: 'today-news-7520b',
    storageBucket: 'today-news-7520b.appspot.com',
    iosBundleId: 'com.example.todayNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiDdNRD7HiOPhVljAn-mCOfXAK2mtu3_A',
    appId: '1:648791294568:web:6d7055929ba9d3eee5f1dd',
    messagingSenderId: '648791294568',
    projectId: 'today-news-7520b',
    authDomain: 'today-news-7520b.firebaseapp.com',
    storageBucket: 'today-news-7520b.appspot.com',
    measurementId: 'G-MSN6Y02JZ0',
  );
}
